on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [hotelsilvercloud]
    steps:
      - uses: actions/checkout@v4
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: netlinkgroup.store
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          remote_path: /var/www/html/${{ matrix.project }}
